from __future__ import annotations

import os
from typing import Any, Literal

from langgraph.graph import END, START, StateGraph

from agents.variant_b.state import VariantBState, VariantBStateUpdate
from memory.checkpointer import create_checkpointer


MAX_RETRIES = 3


def _is_truthy(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def node_gather_context(state: VariantBState) -> VariantBStateUpdate:
    incident = state["incident"]
    context = {
        "incident_id": incident.incident_id,
        "affected_nodes": list(incident.affected_nodes),
        "cargo_demand": incident.cargo_demand,
        "raw_alert_text": incident.raw_alert_text,
    }
    return {"incident_context": context}


def node_generate_scenarios(state: VariantBState) -> VariantBStateUpdate:
    incident_id = state["incident"].incident_id
    retry_count = int(state.get("retry_count", 0))
    scenarios: list[dict[str, Any]] = []
    for index in range(1, 4):
        scenarios.append(
            {
                "scenario_id": f"{incident_id}-S{index}",
                "revision": retry_count,
                "plan_stub": f"stub_plan_{index}_rev_{retry_count}",
                "assumptions_stub": ["placeholder"],
            }
        )
    return {"scenarios": scenarios}


def node_judge_validation(state: VariantBState) -> VariantBStateUpdate:
    retry_count = int(state.get("retry_count", 0))

    force_reject = _is_truthy(os.getenv("VARIANT_B_FORCE_REJECT"))
    verdict = "REJECT" if force_reject else "ACCEPT"

    if verdict == "ACCEPT":
        return {"judge_verdict": "ACCEPT"}

    next_retry = retry_count + 1
    feedback = (
        f"Stub Judge REJECT (retry={next_retry}). "
        "Reason: VARIANT_B_FORCE_REJECT enabled."
    )

    if next_retry >= MAX_RETRIES:
        return {
            "judge_verdict": "REJECT",
            "retry_count": next_retry,
            "judge_feedback": [feedback],
            "fatal_status": "FATAL_VALIDATION_ERROR",
        }

    return {
        "judge_verdict": "REJECT",
        "retry_count": next_retry,
        "judge_feedback": [feedback],
    }


def node_execute_sandbox(state: VariantBState) -> VariantBStateUpdate:
    scenarios = state.get("scenarios", [])
    results: list[dict[str, Any]] = []
    for scenario in scenarios:
        scenario_id = str(scenario.get("scenario_id", "unknown"))
        results.append(
            {
                "scenario_id": scenario_id,
                "metrics_stub": {"throughput": 0, "cost": 0, "delay": 0},
                "status": "MOCKED",
            }
        )
    return {"sandbox_results": results}


def node_synthesize_report(state: VariantBState) -> VariantBStateUpdate:
    incident = state["incident"]
    verdict = state.get("judge_verdict") or "UNKNOWN"
    fatal = state.get("fatal_status")
    retry_count = int(state.get("retry_count", 0))
    report = "\n".join(
        [
            "# Variant B Report (Stub)",
            "",
            f"- incident_id: `{incident.incident_id}`",
            f"- verdict: `{verdict}`",
            f"- retry_count: `{retry_count}`",
            f"- fatal_status: `{fatal}`" if fatal else "- fatal_status: `<none>`",
            "",
            "This is a stub report generated by the Variant B skeleton graph.",
        ]
    )
    return {"final_report_md": report}


def _route_after_judge(
    state: VariantBState,
) -> Literal["node_execute_sandbox", "node_generate_scenarios", "__end__"]:
    if state.get("fatal_status") == "FATAL_VALIDATION_ERROR":
        return "__end__"

    verdict = (state.get("judge_verdict") or "").upper()
    if verdict == "ACCEPT":
        return "node_execute_sandbox"
    return "node_generate_scenarios"


def compile_variant_b_graph():
    workflow: StateGraph = StateGraph(VariantBState)

    workflow.add_node("node_gather_context", node_gather_context)
    workflow.add_node("node_generate_scenarios", node_generate_scenarios)
    workflow.add_node("node_judge_validation", node_judge_validation)
    workflow.add_node("node_execute_sandbox", node_execute_sandbox)
    workflow.add_node("node_synthesize_report", node_synthesize_report)

    workflow.add_edge(START, "node_gather_context")
    workflow.add_edge("node_gather_context", "node_generate_scenarios")
    workflow.add_edge("node_generate_scenarios", "node_judge_validation")

    workflow.add_conditional_edges(
        "node_judge_validation",
        _route_after_judge,
        {
            "node_execute_sandbox": "node_execute_sandbox",
            "node_generate_scenarios": "node_generate_scenarios",
            "__end__": END,
        },
    )

    workflow.add_edge("node_execute_sandbox", "node_synthesize_report")
    workflow.add_edge("node_synthesize_report", END)

    checkpointer = create_checkpointer()
    return workflow.compile(checkpointer=checkpointer)

_CACHED_VARIANT_B_GRAPH: Any | None = None


def get_variant_b_graph():
    global _CACHED_VARIANT_B_GRAPH
    if _CACHED_VARIANT_B_GRAPH is None:
        _CACHED_VARIANT_B_GRAPH = compile_variant_b_graph()
    return _CACHED_VARIANT_B_GRAPH
