from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ToolSpec:
    module: str
    function: str

    @property
    def alias(self) -> str:
        return f"{self.module}__{self.function}"


def _load_manifest(path: Path) -> list[ToolSpec]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise SystemExit(f"Manifest must be a JSON list: {path}")

    specs: list[ToolSpec] = []
    for idx, item in enumerate(raw):
        if not isinstance(item, dict):
            raise SystemExit(f"Manifest entry {idx} must be an object: {path}")
        module = item.get("module")
        function = item.get("function")
        if not isinstance(module, str) or not module:
            raise SystemExit(f"Manifest entry {idx} missing/invalid 'module': {path}")
        if not isinstance(function, str) or not function:
            raise SystemExit(f"Manifest entry {idx} missing/invalid 'function': {path}")
        specs.append(ToolSpec(module=module, function=function))

    aliases = [s.alias for s in specs]
    if len(set(aliases)) != len(aliases):
        raise SystemExit(f"Duplicate tool alias in manifest: {path}")

    return specs


def _render_init(specs: list[ToolSpec]) -> str:
    lines: list[str] = []
    lines.append('"""Curated active skill registry generated by scripts/bootstrap_active_tools.py.')
    lines.append("")
    lines.append("Notes:")
    lines.append("- `ACTIVE_TOOLS` is the canonical runtime export list for the current tool set.")
    lines.append("- Imported tool modules are treated as read-only in benchmarked evaluation workflows.")
    lines.append("- `tools/registry/` is reserved for future dynamic discovery wiring; registration is")
    lines.append("    currently static in this file.")
    lines.append('- The export surface is driven by `tools/active_tools_manifest.json`.')
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")

    for spec in specs:
        lines.append(f"from .{spec.module} import (")
        lines.append(f"    {spec.function} as {spec.alias},")
        lines.append(")")

    lines.append("")
    lines.append("ACTIVE_TOOLS = [")
    for spec in specs:
        lines.append(f"    {spec.alias},")
    lines.append("]")
    lines.append("")
    lines.append("__all__ = [")
    lines.append('    "ACTIVE_TOOLS",')
    for spec in specs:
        lines.append(f'    "{spec.alias}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    default_manifest = repo_root / "tools" / "active_tools_manifest.json"
    tools_init = repo_root / "tools" / "__init__.py"

    parser = argparse.ArgumentParser(description="Generate tools/__init__.py from a manifest.")
    parser.add_argument("--manifest", type=Path, default=default_manifest, help="Path to manifest JSON.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Exit non-zero if tools/__init__.py is out of date.")
    mode.add_argument("--write", action="store_true", help="Rewrite tools/__init__.py from the manifest.")
    args = parser.parse_args()

    specs = _load_manifest(args.manifest)
    rendered = _render_init(specs)

    current = tools_init.read_text(encoding="utf-8") if tools_init.exists() else ""
    if args.check:
        if current != rendered:
            print("tools/__init__.py is out of date.")
            print("Run: uv run python scripts/bootstrap_active_tools.py --write")
            return 1
        return 0

    tools_init.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

