"""Curated active skill registry generated by scripts/bootstrap_active_tools.py.

Notes:
- `ACTIVE_TOOLS` is the canonical runtime export list for the current tool set.
- Imported tool modules are treated as read-only in benchmarked evaluation workflows.
- `tools/registry/` is reserved for future dynamic discovery wiring; registration is
    currently static in this file.
- The export surface is driven by `tools/active_tools_manifest.json`.
"""

from __future__ import annotations

from .economic_order_quantity import (
    calculate_total_annual_inventory_cost as economic_order_quantity__calculate_total_annual_inventory_cost,
)
from .reorder_point_safety_stock import (
    calculate_reorder_point_safety_stock as reorder_point_safety_stock__calculate_reorder_point_safety_stock,
)
from .newsvendor_model import (
    evaluate_newsvendor_strategy as newsvendor_model__evaluate_newsvendor_strategy,
)
from .abc_classification import (
    abc_inventory_categorization as abc_classification__abc_inventory_categorization,
)
from .bullwhip_effect import (
    bullwhip_effect_identifier as bullwhip_effect__bullwhip_effect_identifier,
)
from .risk_pooling import (
    demand_aggregation_safety_stock_reduction as risk_pooling__demand_aggregation_safety_stock_reduction,
)
from .inventory_turnover import (
    calculate_inventory_turnover as inventory_turnover__calculate_inventory_turnover,
)
from .mrp_net_requirements import (
    calculate_net_requirements as mrp_net_requirements__calculate_net_requirements,
)
from .mps_projected_available_balance import (
    compute_projected_available_balance as mps_projected_available_balance__compute_projected_available_balance,
)
from .aggregate_planning_optimizer import (
    solve_aggregate_planning as aggregate_planning_optimizer__solve_aggregate_planning,
)
from .work_center_load import (
    calculate_work_center_load as work_center_load__calculate_work_center_load,
)
from .toc_bottleneck_analysis import (
    analyze_toc_scheduling as toc_bottleneck_analysis__analyze_toc_scheduling,
)
from .pert_cpm_variance import (
    aggregate_critical_path_variance as pert_cpm_variance__aggregate_critical_path_variance,
)
from .mrp_pegging import (
    mrp_pegging_tracing as mrp_pegging__mrp_pegging_tracing,
)
from .edd_dispatching import (
    select_edd_job as edd_dispatching__select_edd_job,
)
from .pareto_analysis import (
    apply_pareto_principle as pareto_analysis__apply_pareto_principle,
)
from .fmea_rpn import (
    calculate_rpn as fmea_rpn__calculate_rpn,
)
from .xbar_s_control_charts import (
    calculate_control_limits as xbar_s_control_charts__calculate_control_limits,
)
from .p_chart_ucl import (
    calculate_ucl_p_chart as p_chart_ucl__calculate_ucl_p_chart,
)
from .process_capability_cpk import (
    calculate_process_capability_indices as process_capability_cpk__calculate_process_capability_indices,
)
from .facility_location_optimizer import (
    optimize_facility_location as facility_location_optimizer__optimize_facility_location,
)
from .centroid_location import (
    main as centroid_location__main,
)
from .ocean_freight_costing import (
    calculate_total_freight_cost as ocean_freight_costing__calculate_total_freight_cost,
)
from .transport_route_savings import (
    calculate_direct_rotation_cost_savings as transport_route_savings__calculate_direct_rotation_cost_savings,
)
from .terminal_throughput import (
    calculate_terminal_truck_capacity as terminal_throughput__calculate_terminal_truck_capacity,
)
from .kraljic_matrix import (
    kraljic_supply_matrix_classification as kraljic_matrix__kraljic_supply_matrix_classification,
)
from .risk_sharing_contracts import (
    optimize_risk_sharing_contract as risk_sharing_contracts__optimize_risk_sharing_contract,
)
from .make_or_buy import (
    make_buy_decision as make_or_buy__make_buy_decision,
)
from .pricing_optimization import (
    optimal_retail_pricing as pricing_optimization__optimal_retail_pricing,
)
from .linear_trend_forecast import (
    linear_trend_forecast as linear_trend_forecast__linear_trend_forecast,
)
from .seasonal_decomposition import (
    calculate_seasonal_indices as seasonal_decomposition__calculate_seasonal_indices,
)
from .return_on_assets import (
    calculate_return_on_total_assets as return_on_assets__calculate_return_on_total_assets,
)
from .pestel_analysis import (
    perform_pestel_analysis as pestel_analysis__perform_pestel_analysis,
)
from .moving_average import (
    moving_average_forecast as moving_average__moving_average_forecast,
)
from .apics_rule_check import (
    validate_scm_reasoning as apics_rule_check__validate_scm_reasoning,
)

ACTIVE_TOOLS = [
    economic_order_quantity__calculate_total_annual_inventory_cost,
    reorder_point_safety_stock__calculate_reorder_point_safety_stock,
    newsvendor_model__evaluate_newsvendor_strategy,
    abc_classification__abc_inventory_categorization,
    bullwhip_effect__bullwhip_effect_identifier,
    risk_pooling__demand_aggregation_safety_stock_reduction,
    inventory_turnover__calculate_inventory_turnover,
    mrp_net_requirements__calculate_net_requirements,
    mps_projected_available_balance__compute_projected_available_balance,
    aggregate_planning_optimizer__solve_aggregate_planning,
    work_center_load__calculate_work_center_load,
    toc_bottleneck_analysis__analyze_toc_scheduling,
    pert_cpm_variance__aggregate_critical_path_variance,
    mrp_pegging__mrp_pegging_tracing,
    edd_dispatching__select_edd_job,
    pareto_analysis__apply_pareto_principle,
    fmea_rpn__calculate_rpn,
    xbar_s_control_charts__calculate_control_limits,
    p_chart_ucl__calculate_ucl_p_chart,
    process_capability_cpk__calculate_process_capability_indices,
    facility_location_optimizer__optimize_facility_location,
    centroid_location__main,
    ocean_freight_costing__calculate_total_freight_cost,
    transport_route_savings__calculate_direct_rotation_cost_savings,
    terminal_throughput__calculate_terminal_truck_capacity,
    kraljic_matrix__kraljic_supply_matrix_classification,
    risk_sharing_contracts__optimize_risk_sharing_contract,
    make_or_buy__make_buy_decision,
    pricing_optimization__optimal_retail_pricing,
    linear_trend_forecast__linear_trend_forecast,
    seasonal_decomposition__calculate_seasonal_indices,
    return_on_assets__calculate_return_on_total_assets,
    pestel_analysis__perform_pestel_analysis,
    moving_average__moving_average_forecast,
    apics_rule_check__validate_scm_reasoning,
]

__all__ = [
    "ACTIVE_TOOLS",
    "economic_order_quantity__calculate_total_annual_inventory_cost",
    "reorder_point_safety_stock__calculate_reorder_point_safety_stock",
    "newsvendor_model__evaluate_newsvendor_strategy",
    "abc_classification__abc_inventory_categorization",
    "bullwhip_effect__bullwhip_effect_identifier",
    "risk_pooling__demand_aggregation_safety_stock_reduction",
    "inventory_turnover__calculate_inventory_turnover",
    "mrp_net_requirements__calculate_net_requirements",
    "mps_projected_available_balance__compute_projected_available_balance",
    "aggregate_planning_optimizer__solve_aggregate_planning",
    "work_center_load__calculate_work_center_load",
    "toc_bottleneck_analysis__analyze_toc_scheduling",
    "pert_cpm_variance__aggregate_critical_path_variance",
    "mrp_pegging__mrp_pegging_tracing",
    "edd_dispatching__select_edd_job",
    "pareto_analysis__apply_pareto_principle",
    "fmea_rpn__calculate_rpn",
    "xbar_s_control_charts__calculate_control_limits",
    "p_chart_ucl__calculate_ucl_p_chart",
    "process_capability_cpk__calculate_process_capability_indices",
    "facility_location_optimizer__optimize_facility_location",
    "centroid_location__main",
    "ocean_freight_costing__calculate_total_freight_cost",
    "transport_route_savings__calculate_direct_rotation_cost_savings",
    "terminal_throughput__calculate_terminal_truck_capacity",
    "kraljic_matrix__kraljic_supply_matrix_classification",
    "risk_sharing_contracts__optimize_risk_sharing_contract",
    "make_or_buy__make_buy_decision",
    "pricing_optimization__optimal_retail_pricing",
    "linear_trend_forecast__linear_trend_forecast",
    "seasonal_decomposition__calculate_seasonal_indices",
    "return_on_assets__calculate_return_on_total_assets",
    "pestel_analysis__perform_pestel_analysis",
    "moving_average__moving_average_forecast",
    "apics_rule_check__validate_scm_reasoning",
]
